package com.xidian.yetwish.reading.framework.database.generator;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table BOOK.
 */
public class Book {

    private Long bookId;
    private String name;
    private String author;
    private String language;
    private Float progress;
    private String iconPath;
    private Integer iconResId;
    private String path;
    private Long charNumber;

    public Book() {
    }

    public Book(Long bookId) {
        this.bookId = bookId;
    }

    public Book(Long bookId, String name, String author, String language, Float progress, String iconPath, Integer iconResId, String path, Long charNumber) {
        this.bookId = bookId;
        this.name = name;
        this.author = author;
        this.language = language;
        this.progress = progress;
        this.iconPath = iconPath;
        this.iconResId = iconResId;
        this.path = path;
        this.charNumber = charNumber;
    }

    public Long getBookId() {
        return bookId;
    }

    public void setBookId(Long bookId) {
        this.bookId = bookId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public String getLanguage() {
        return language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

    public Float getProgress() {
        return progress;
    }

    public void setProgress(Float progress) {
        this.progress = progress;
    }

    public String getIconPath() {
        return iconPath;
    }

    public void setIconPath(String iconPath) {
        this.iconPath = iconPath;
    }

    public Integer getIconResId() {
        return iconResId;
    }

    public void setIconResId(Integer iconResId) {
        this.iconResId = iconResId;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public Long getCharNumber() {
        return charNumber;
    }

    public void setCharNumber(Long charNumber) {
        this.charNumber = charNumber;
    }

}
