package com.xidian.yetwish.reading.framework.database.generator;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.xidian.yetwish.reading.framework.database.generator.Chapter;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table CHAPTER.
*/
public class ChapterDao extends AbstractDao<Chapter, Long> {

    public static final String TABLENAME = "CHAPTER";

    /**
     * Properties of entity Chapter.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ChapterId = new Property(1, String.class, "chapterId", false, "CHAPTER_ID");
        public final static Property BookId = new Property(2, String.class, "bookId", false, "BOOK_ID");
        public final static Property Path = new Property(3, String.class, "path", false, "PATH");
        public final static Property Name = new Property(4, String.class, "name", false, "NAME");
        public final static Property FirstCharPosition = new Property(5, Long.class, "firstCharPosition", false, "FIRST_CHAR_POSITION");
        public final static Property LastCharPosition = new Property(6, Long.class, "lastCharPosition", false, "LAST_CHAR_POSITION");
        public final static Property PageNumber = new Property(7, Integer.class, "pageNumber", false, "PAGE_NUMBER");
    };


    public ChapterDao(DaoConfig config) {
        super(config);
    }
    
    public ChapterDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'CHAPTER' (" + //
                "'_id' INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "'CHAPTER_ID' TEXT," + // 1: chapterId
                "'BOOK_ID' TEXT," + // 2: bookId
                "'PATH' TEXT," + // 3: path
                "'NAME' TEXT," + // 4: name
                "'FIRST_CHAR_POSITION' INTEGER," + // 5: firstCharPosition
                "'LAST_CHAR_POSITION' INTEGER," + // 6: lastCharPosition
                "'PAGE_NUMBER' INTEGER);"); // 7: pageNumber
        // Add Indexes
        db.execSQL("CREATE UNIQUE INDEX " + constraint + "IDX_CHAPTER_CHAPTER_ID_BOOK_ID ON CHAPTER" +
                " (CHAPTER_ID,BOOK_ID);");
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'CHAPTER'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Chapter entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String chapterId = entity.getChapterId();
        if (chapterId != null) {
            stmt.bindString(2, chapterId);
        }
 
        String bookId = entity.getBookId();
        if (bookId != null) {
            stmt.bindString(3, bookId);
        }
 
        String path = entity.getPath();
        if (path != null) {
            stmt.bindString(4, path);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(5, name);
        }
 
        Long firstCharPosition = entity.getFirstCharPosition();
        if (firstCharPosition != null) {
            stmt.bindLong(6, firstCharPosition);
        }
 
        Long lastCharPosition = entity.getLastCharPosition();
        if (lastCharPosition != null) {
            stmt.bindLong(7, lastCharPosition);
        }
 
        Integer pageNumber = entity.getPageNumber();
        if (pageNumber != null) {
            stmt.bindLong(8, pageNumber);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Chapter readEntity(Cursor cursor, int offset) {
        Chapter entity = new Chapter( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // chapterId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // bookId
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // path
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // name
            cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5), // firstCharPosition
            cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6), // lastCharPosition
            cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7) // pageNumber
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Chapter entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setChapterId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setBookId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setPath(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setName(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setFirstCharPosition(cursor.isNull(offset + 5) ? null : cursor.getLong(offset + 5));
        entity.setLastCharPosition(cursor.isNull(offset + 6) ? null : cursor.getLong(offset + 6));
        entity.setPageNumber(cursor.isNull(offset + 7) ? null : cursor.getInt(offset + 7));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Chapter entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Chapter entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
