package com.xidian.yetwish.reading.framework.database.generator;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table DEPARTMENT.
 */
public class Department {

    private Long id;
    private Long orgId;
    private Long departmentId;
    private Long parentId;
    private Long userCounts;
    private Integer sequence;
    private String name;
    private String description;
    private String parentIds;
    private String orgName;

    public Department() {
    }

    public Department(Long id) {
        this.id = id;
    }

    public Department(Long id, Long orgId, Long departmentId, Long parentId, Long userCounts, Integer sequence, String name, String description, String parentIds, String orgName) {
        this.id = id;
        this.orgId = orgId;
        this.departmentId = departmentId;
        this.parentId = parentId;
        this.userCounts = userCounts;
        this.sequence = sequence;
        this.name = name;
        this.description = description;
        this.parentIds = parentIds;
        this.orgName = orgName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getOrgId() {
        return orgId;
    }

    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    public Long getDepartmentId() {
        return departmentId;
    }

    public void setDepartmentId(Long departmentId) {
        this.departmentId = departmentId;
    }

    public Long getParentId() {
        return parentId;
    }

    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    public Long getUserCounts() {
        return userCounts;
    }

    public void setUserCounts(Long userCounts) {
        this.userCounts = userCounts;
    }

    public Integer getSequence() {
        return sequence;
    }

    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public String getParentIds() {
        return parentIds;
    }

    public void setParentIds(String parentIds) {
        this.parentIds = parentIds;
    }

    public String getOrgName() {
        return orgName;
    }

    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

}
