package com.xidian.yetwish.reading.framework.database.generator;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table GROUP_MEMBER.
 */
public class GroupMember {

    private Long id;
    private Long cid;
    private String uid;
    private String userName;

    public GroupMember() {
    }

    public GroupMember(Long id) {
        this.id = id;
    }

    public GroupMember(Long id, Long cid, String uid, String userName) {
        this.id = id;
        this.cid = cid;
        this.uid = uid;
        this.userName = userName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getCid() {
        return cid;
    }

    public void setCid(Long cid) {
        this.cid = cid;
    }

    public String getUid() {
        return uid;
    }

    public void setUid(String uid) {
        this.uid = uid;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

}
