package com.xidian.yetwish.reading.framework.database.generator;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.xidian.yetwish.reading.framework.database.generator.NoteBook;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table NOTE_BOOK.
*/
public class NoteBookDao extends AbstractDao<NoteBook, Long> {

    public static final String TABLENAME = "NOTE_BOOK";

    /**
     * Properties of entity NoteBook.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property NoteBookId = new Property(0, Long.class, "NoteBookId", true, "NOTE_BOOK_ID");
        public final static Property BookId = new Property(1, Long.class, "bookId", false, "BOOK_ID");
        public final static Property Name = new Property(2, String.class, "name", false, "NAME");
        public final static Property IconResId = new Property(3, Integer.class, "iconResId", false, "ICON_RES_ID");
        public final static Property NoteNumber = new Property(4, Integer.class, "noteNumber", false, "NOTE_NUMBER");
        public final static Property Intro = new Property(5, String.class, "intro", false, "INTRO");
    };


    public NoteBookDao(DaoConfig config) {
        super(config);
    }
    
    public NoteBookDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'NOTE_BOOK' (" + //
                "'NOTE_BOOK_ID' INTEGER PRIMARY KEY ," + // 0: NoteBookId
                "'BOOK_ID' INTEGER," + // 1: bookId
                "'NAME' TEXT," + // 2: name
                "'ICON_RES_ID' INTEGER," + // 3: iconResId
                "'NOTE_NUMBER' INTEGER," + // 4: noteNumber
                "'INTRO' TEXT);"); // 5: intro
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'NOTE_BOOK'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, NoteBook entity) {
        stmt.clearBindings();
 
        Long NoteBookId = entity.getNoteBookId();
        if (NoteBookId != null) {
            stmt.bindLong(1, NoteBookId);
        }
 
        Long bookId = entity.getBookId();
        if (bookId != null) {
            stmt.bindLong(2, bookId);
        }
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(3, name);
        }
 
        Integer iconResId = entity.getIconResId();
        if (iconResId != null) {
            stmt.bindLong(4, iconResId);
        }
 
        Integer noteNumber = entity.getNoteNumber();
        if (noteNumber != null) {
            stmt.bindLong(5, noteNumber);
        }
 
        String intro = entity.getIntro();
        if (intro != null) {
            stmt.bindString(6, intro);
        }
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public NoteBook readEntity(Cursor cursor, int offset) {
        NoteBook entity = new NoteBook( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // NoteBookId
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // bookId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // name
            cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3), // iconResId
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // noteNumber
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // intro
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, NoteBook entity, int offset) {
        entity.setNoteBookId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setBookId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setName(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setIconResId(cursor.isNull(offset + 3) ? null : cursor.getInt(offset + 3));
        entity.setNoteNumber(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setIntro(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(NoteBook entity, long rowId) {
        entity.setNoteBookId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(NoteBook entity) {
        if(entity != null) {
            return entity.getNoteBookId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
