package com.xidian.yetwish.reading.framework.database.generator;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table NOTE.
 */
public class Note {

    private Long id;
    private String NoteBookId;
    private String noteId;
    private String name;
    private String path;

    public Note() {
    }

    public Note(Long id) {
        this.id = id;
    }

    public Note(Long id, String NoteBookId, String noteId, String name, String path) {
        this.id = id;
        this.NoteBookId = NoteBookId;
        this.noteId = noteId;
        this.name = name;
        this.path = path;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNoteBookId() {
        return NoteBookId;
    }

    public void setNoteBookId(String NoteBookId) {
        this.NoteBookId = NoteBookId;
    }

    public String getNoteId() {
        return noteId;
    }

    public void setNoteId(String noteId) {
        this.noteId = noteId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

}
