package com.xidian.yetwish.reading.framework.database.generator;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table NOTE_BOOK.
 */
public class NoteBook {

    private Long id;
    private Long NoteBookId;
    private Long noteId;
    private String name;
    private String path;

    public NoteBook() {
    }

    public NoteBook(Long id) {
        this.id = id;
    }

    public NoteBook(Long id, Long NoteBookId, Long noteId, String name, String path) {
        this.id = id;
        this.NoteBookId = NoteBookId;
        this.noteId = noteId;
        this.name = name;
        this.path = path;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getNoteBookId() {
        return NoteBookId;
    }

    public void setNoteBookId(Long NoteBookId) {
        this.NoteBookId = NoteBookId;
    }

    public Long getNoteId() {
        return noteId;
    }

    public void setNoteId(Long noteId) {
        this.noteId = noteId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

}
