package com.xidian.yetwish.reading.framework.database.generator;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table NOTE_BOOK.
 */
public class NoteBook {

    private Long id;
    private String NoteBookId;
    private String bookId;
    private String name;
    private String iconPath;
    private Integer noteNumber;
    private String intro;

    public NoteBook() {
    }

    public NoteBook(Long id) {
        this.id = id;
    }

    public NoteBook(Long id, String NoteBookId, String bookId, String name, String iconPath, Integer noteNumber, String intro) {
        this.id = id;
        this.NoteBookId = NoteBookId;
        this.bookId = bookId;
        this.name = name;
        this.iconPath = iconPath;
        this.noteNumber = noteNumber;
        this.intro = intro;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNoteBookId() {
        return NoteBookId;
    }

    public void setNoteBookId(String NoteBookId) {
        this.NoteBookId = NoteBookId;
    }

    public String getBookId() {
        return bookId;
    }

    public void setBookId(String bookId) {
        this.bookId = bookId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getIconPath() {
        return iconPath;
    }

    public void setIconPath(String iconPath) {
        this.iconPath = iconPath;
    }

    public Integer getNoteNumber() {
        return noteNumber;
    }

    public void setNoteNumber(Integer noteNumber) {
        this.noteNumber = noteNumber;
    }

    public String getIntro() {
        return intro;
    }

    public void setIntro(String intro) {
        this.intro = intro;
    }

}
