package com.xidian.yetwish.reading.framework.database.generator;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PAGE.
 */
public class Page {

    private Long id;
    private String pageId;
    private String chapterId;
    private String bookId;
    private Long firstCharPosition;
    private Long lastCharPosition;
    private String path;
    private String content;

    public Page() {
    }

    public Page(Long id) {
        this.id = id;
    }

    public Page(Long id, String pageId, String chapterId, String bookId, Long firstCharPosition, Long lastCharPosition, String path, String content) {
        this.id = id;
        this.pageId = pageId;
        this.chapterId = chapterId;
        this.bookId = bookId;
        this.firstCharPosition = firstCharPosition;
        this.lastCharPosition = lastCharPosition;
        this.path = path;
        this.content = content;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getPageId() {
        return pageId;
    }

    public void setPageId(String pageId) {
        this.pageId = pageId;
    }

    public String getChapterId() {
        return chapterId;
    }

    public void setChapterId(String chapterId) {
        this.chapterId = chapterId;
    }

    public String getBookId() {
        return bookId;
    }

    public void setBookId(String bookId) {
        this.bookId = bookId;
    }

    public Long getFirstCharPosition() {
        return firstCharPosition;
    }

    public void setFirstCharPosition(Long firstCharPosition) {
        this.firstCharPosition = firstCharPosition;
    }

    public Long getLastCharPosition() {
        return lastCharPosition;
    }

    public void setLastCharPosition(Long lastCharPosition) {
        this.lastCharPosition = lastCharPosition;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

}
