package com.xidian.yetwish.reading.framework.database.generator;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table PAGE.
 */
public class Page {

    private Long pageId;
    private Long chapterId;
    private Long bookId;
    private Long firstCharPosition;
    private Long lastCharPosition;
    private String path;
    private String content;

    public Page() {
    }

    public Page(Long pageId) {
        this.pageId = pageId;
    }

    public Page(Long pageId, Long chapterId, Long bookId, Long firstCharPosition, Long lastCharPosition, String path, String content) {
        this.pageId = pageId;
        this.chapterId = chapterId;
        this.bookId = bookId;
        this.firstCharPosition = firstCharPosition;
        this.lastCharPosition = lastCharPosition;
        this.path = path;
        this.content = content;
    }

    public Long getPageId() {
        return pageId;
    }

    public void setPageId(Long pageId) {
        this.pageId = pageId;
    }

    public Long getChapterId() {
        return chapterId;
    }

    public void setChapterId(Long chapterId) {
        this.chapterId = chapterId;
    }

    public Long getBookId() {
        return bookId;
    }

    public void setBookId(Long bookId) {
        this.bookId = bookId;
    }

    public Long getFirstCharPosition() {
        return firstCharPosition;
    }

    public void setFirstCharPosition(Long firstCharPosition) {
        this.firstCharPosition = firstCharPosition;
    }

    public Long getLastCharPosition() {
        return lastCharPosition;
    }

    public void setLastCharPosition(Long lastCharPosition) {
        this.lastCharPosition = lastCharPosition;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }

    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

}
