package com.xidian.yetwish.reading.framework.database.generator;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table USER.
 */
public class User {

    private Long id;
    private Long uid;
    private Long orgId;
    private Long departmentId;
    private Integer sequence;
    private String mobile;
    private String title;
    private String name;
    private String pinyin;
    private Integer sex;
    private String email;
    private String homePhone;
    private String personalCellPhone;
    private String shortNum;
    private String shortNum2;
    private String workPhone;
    private String workPhone2;
    private String virtualCellPhone;
    private String remark;
    private Boolean isAllowLogin;
    private String virtualCode;
    private String fax;
    private String shortPinyin;
    private String customField;
    private String privilege;
    private String orgName;

    public User() {
    }

    public User(Long id) {
        this.id = id;
    }

    public User(Long id, Long uid, Long orgId, Long departmentId, Integer sequence, String mobile, String title, String name, String pinyin, Integer sex, String email, String homePhone, String personalCellPhone, String shortNum, String shortNum2, String workPhone, String workPhone2, String virtualCellPhone, String remark, Boolean isAllowLogin, String virtualCode, String fax, String shortPinyin, String customField, String privilege, String orgName) {
        this.id = id;
        this.uid = uid;
        this.orgId = orgId;
        this.departmentId = departmentId;
        this.sequence = sequence;
        this.mobile = mobile;
        this.title = title;
        this.name = name;
        this.pinyin = pinyin;
        this.sex = sex;
        this.email = email;
        this.homePhone = homePhone;
        this.personalCellPhone = personalCellPhone;
        this.shortNum = shortNum;
        this.shortNum2 = shortNum2;
        this.workPhone = workPhone;
        this.workPhone2 = workPhone2;
        this.virtualCellPhone = virtualCellPhone;
        this.remark = remark;
        this.isAllowLogin = isAllowLogin;
        this.virtualCode = virtualCode;
        this.fax = fax;
        this.shortPinyin = shortPinyin;
        this.customField = customField;
        this.privilege = privilege;
        this.orgName = orgName;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getUid() {
        return uid;
    }

    public void setUid(Long uid) {
        this.uid = uid;
    }

    public Long getOrgId() {
        return orgId;
    }

    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    public Long getDepartmentId() {
        return departmentId;
    }

    public void setDepartmentId(Long departmentId) {
        this.departmentId = departmentId;
    }

    public Integer getSequence() {
        return sequence;
    }

    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPinyin() {
        return pinyin;
    }

    public void setPinyin(String pinyin) {
        this.pinyin = pinyin;
    }

    public Integer getSex() {
        return sex;
    }

    public void setSex(Integer sex) {
        this.sex = sex;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getHomePhone() {
        return homePhone;
    }

    public void setHomePhone(String homePhone) {
        this.homePhone = homePhone;
    }

    public String getPersonalCellPhone() {
        return personalCellPhone;
    }

    public void setPersonalCellPhone(String personalCellPhone) {
        this.personalCellPhone = personalCellPhone;
    }

    public String getShortNum() {
        return shortNum;
    }

    public void setShortNum(String shortNum) {
        this.shortNum = shortNum;
    }

    public String getShortNum2() {
        return shortNum2;
    }

    public void setShortNum2(String shortNum2) {
        this.shortNum2 = shortNum2;
    }

    public String getWorkPhone() {
        return workPhone;
    }

    public void setWorkPhone(String workPhone) {
        this.workPhone = workPhone;
    }

    public String getWorkPhone2() {
        return workPhone2;
    }

    public void setWorkPhone2(String workPhone2) {
        this.workPhone2 = workPhone2;
    }

    public String getVirtualCellPhone() {
        return virtualCellPhone;
    }

    public void setVirtualCellPhone(String virtualCellPhone) {
        this.virtualCellPhone = virtualCellPhone;
    }

    public String getRemark() {
        return remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

    public Boolean getIsAllowLogin() {
        return isAllowLogin;
    }

    public void setIsAllowLogin(Boolean isAllowLogin) {
        this.isAllowLogin = isAllowLogin;
    }

    public String getVirtualCode() {
        return virtualCode;
    }

    public void setVirtualCode(String virtualCode) {
        this.virtualCode = virtualCode;
    }

    public String getFax() {
        return fax;
    }

    public void setFax(String fax) {
        this.fax = fax;
    }

    public String getShortPinyin() {
        return shortPinyin;
    }

    public void setShortPinyin(String shortPinyin) {
        this.shortPinyin = shortPinyin;
    }

    public String getCustomField() {
        return customField;
    }

    public void setCustomField(String customField) {
        this.customField = customField;
    }

    public String getPrivilege() {
        return privilege;
    }

    public void setPrivilege(String privilege) {
        this.privilege = privilege;
    }

    public String getOrgName() {
        return orgName;
    }

    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

}
